log:
  level: debug
  disable_sentry: true

collector:
  endpoint: "http://order-aggregator/integrations/order-aggregator"
  request_timeout: 1s

network:
  rpc: "http://rpc-proxy/integrations/rpc-proxy/goerli"
  contract: "Swapica address"
  chain_id: 5
  index_period: 10s
  request_timeout: 3s